#! /bin/bash

### BEGIN INIT INFO
# Provides:		rov
# Required-Start:	$syslog
# Required-Stop:	$syslog
# Default-Start:	2 3 4 5
# Default-Stop:		
# Short-Description:	SHSROV Server
### END INIT INFO

set -e

# /etc/init.d/rov: start and stop the Moki ROV server daemon

umask 022

#if test -f /etc/default/rov; then
#    . /etc/default/rov
    . /home/pi/SHS-ROV/rov.default
#fi

export PATH=$PATH:/usr/local/bin
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules

. /lib/lsb/init-functions

# Are we running from init?
run_by_init() {
    ([ "$previous" ] && [ "$runlevel" ]) || [ "$runlevel" = S ]
}

cd /home/pi/SHS-ROV

rov_start() {
   echo "Starting RTIMULibDrive for IMU support."
   RTIMULibDrive > /home/pi/SHS-ROV/RTIMULib.log 2>&1 &
   
   echo "Starting Camera support."
   if [ $CAM1 == "ON" ] 
   then
     echo "Starting Cam1."
     exec /home/pi/mjpg-streamer/mjpg_streamer -i "/home/pi/mjpg-streamer/input_uvc.so -n -f 5 -r 800x600 -d /dev/video0" -o "/home/pi/mjpg-streamer/output_http.so  -n -w /home/pi/mjpg-streamer/www -p 8080" &
   fi
   if [ $CAM2 == "ON" ] 
   then
     echo "Starting Cam2."
     exec /home/pi/mjpg-streamer/mjpg_streamer -i "/home/pi/mjpg-streamer/input_uvc.so -n -f 5 -r 800x600 -d /dev/video1" -o "/home/pi/mjpg-streamer/output_http.so  -n -w /home/pi/mjpg-streamer/www -p 8081" &
   fi
   if [ $CAM3 == "ON" ] 
   then
     echo "Starting Cam3."
     exec /home/pi/mjpg-streamer/mjpg_streamer -i "/home/pi/mjpg-streamer/input_uvc.so -n -f 5 -r 800x600 -d /dev/video2" -o "/home/pi/mjpg-streamer/output_http.so  -n -w /home/pi/mjpg-streamer/www -p 8082" &
   fi
   if [ $CAM4 == "ON" ] 
   then
     echo "Starting Cam4."
     mjpg_streamer -i "./input_uvc.so -n -f 24 -r 800x600 -d /dev/video3" -o "./output_http.so  -n -w /usr/local/www -p 8080" &
   fi

   echo "Starting ROV server."
   #forever --sourceDir=/home/pi/SHS-ROV -l /home/pi/SHS-ROV/server.log start app.js
   forever app.js &
   echo "Done Starting"
}

rov_stop() {
   echo "Stopping ROV server."
   forever stop /home/pi/SHS-ROV/app.js
   echo "Stopping mjpg_streamer."
   killall -9 -q mjpg_streamer;
   echo "Stopping RTIMULibDrive."
   killall -9 -q RTIMULibDrive;
}

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
  start)
	log_daemon_msg "Starting SHS-ROV server" "rov" || true
    	echo;
	rov_start;
	;;
  stop)
	log_daemon_msg "Stopping SHS-ROV server" "rov" || true
    	echo;
	rov_stop;
	;;

  restart)
	log_daemon_msg "Stopping SHS-ROV server" "rov" || true
    	echo;
	rov_stop;
	log_daemon_msg "Starting SHS-ROV server" "rov" || true
    	echo;
	rov_start;
	;;

  *)
	log_action_msg "Usage: /etc/init.d/rov {start|stop|restart}" || true
	exit 1
esac

exit 0
